# Chargement des APLs

In [94]:
import pandas as pd
from pathlib import Path

# On essaie d'utiliser __file__, sinon on prend le dossier actuel
try:
    BASE_DIR = Path(__file__).resolve().parent
except NameError:
    BASE_DIR = Path.cwd()

ROOT = BASE_DIR.parent
DATA_DIR = ROOT / "data/raw/offres_soins"

%ls ../data/raw/offres_soins

print(DATA_DIR)


dfs_2022 = []

apl_chirurgiens_dentistes.xlsx  apl_medecins_generalistes.xlsx
apl_infirmieres.xlsx            apl_moyennes_dixiemes.xlsx
apl_kinesitherapeutes.xlsx      apl_sages_femmes.xlsx
/Users/jean-jacques/code/jjchabutDataCRM/sante-territoires/data/raw/offres_soins

## 1  - Chargement APL médecins

In [95]:
print("1 - Chargement APL Médecins généralistes ...")
file_path = DATA_DIR / 'apl_medecins_generalistes.xlsx'

df_apl_medecins = pd.read_excel(
    #'../data/raw/offres_soins/apl_medecins_generalistes.xlsx',
    file_path,
    sheet_name='APL 2023',
    skiprows=8,
    dtype={'Code commune INSEE': str}
).rename(columns={
    'Code commune INSEE': 'code_insee_comm',
    'Commune': 'nom_commune',
    'APL aux médecins généralistes': 'apl_medecins',
    'APL aux médecins généralistes de 65 ans et moins ': 'apl_65ans',
    'APL aux médecins généralistes de 62 ans et moins ': 'apl_62ans',
    'APL aux médecins généralistes de 60 ans et moins ': 'apl_60ans',
    'Population standardisée 2021 pour la médecine générale': 'pop_standard_2021',
    'Population totale 2021': 'pop_totale_2021'
    })

print(f"{len(df_apl_medecins):,} lignes chargées")
print(f"Colonnes : {df_apl_medecins.columns.tolist()}")

df_apl_med_2022 = pd.read_excel( 
        file_path,
        sheet_name='APL 2022',
        skiprows=8, dtype={'Code commune INSEE': str}
    ).rename(columns={
        'Code commune INSEE': 'code_insee_comm',
        'APL aux médecins généralistes': 'apl_medecins_2022',
        'APL aux médecins généralistes de 65 ans et moins ': 'apl_65a_2022',
        'APL aux médecins généralistes de 62 ans et moins ': 'apl_62a_2022',
        'APL aux médecins généralistes de 60 ans et moins ': 'apl_60a_2022',}
        )
[['Code commune INSEE', 'apl_medecins_prec', 'apl_65a_prec', 'apl_62a_prec', 'apl_60a_prec']]

dfs_2022.append(df_apl_med_2022)

1 - Chargement APL Médecins généralistes ...
34,955 lignes chargées
Colonnes : ['code_insee_comm', 'nom_commune', 'apl_medecins', 'apl_65ans', 'apl_62ans', 'apl_60ans', 'pop_standard_2021', 'pop_totale_2021']

In [96]:
df_apl_med_2022.head()

,code_insee_comm,Commune,apl_medecins_2022,apl_65a_2022,apl_62a_2022,apl_60a_2022,Population standardisée 2020 pour la médecine générale,Population totale 2020
0,NaN,NaN,En nombre de consultations/visites accessibles...,En nombre de consultations/visites accessibles...,En nombre de consultations/visites accessibles...,En nombre de consultations/visites accessibles...,En nombre d'habitants standardisés,En nombre d'habitants
1,01001,L'Abergement-Clémenciat,1.89,1.828,1.799,1.491,810.855,806
2,01002,L'Abergement-de-Varey,2.649,2.059,1.83,1.493,250.962,262
3,01004,Ambérieu-en-Bugey,3.646,2.88,2.697,2.253,14002.685,14288
4,01005,Ambérieux-en-Dombes,3.978,3.959,3.312,3.041,1733.232,1782

## 2  - Chargement APL dentistes

In [97]:
print('-'*50)
print("2 - Chargement APL chirurgiens-dentistes ...")
file_path = DATA_DIR / 'apl_chirurgiens_dentistes.xlsx'
df_apl_dentistes = pd.read_excel(
    file_path,
    sheet_name='APL 2023',
    skiprows=8,
    dtype={'Code commune INSEE': str}
).rename(columns={'APL aux chirurgiens-dentistes': 'apl_dentistes',
                  'Code commune INSEE': 'code_insee_comm',
                  'Commune': 'nom_commune'})

print(f"{len(df_apl_dentistes):,} lignes chargées")
print(f"Colonnes : {df_apl_dentistes.columns.tolist()}")
print("\n🔍 Vérification des valeurs :")
print(df_apl_dentistes[['code_insee_comm', 'nom_commune', 'apl_dentistes']].head(10))

df_apl_dent_2022 = (
    pd.read_excel(
        file_path,
        sheet_name='APL 2022',
        skiprows=8,
        dtype={'Code commune INSEE': str}
    )
    .rename(columns={'APL aux chirurgiens-dentistes': 'apl_dentistes_2022',
                     'Code commune INSEE': 'code_insee_comm'})
    [['code_insee_comm', 'apl_dentistes_2022']]
) 
dfs_2022.append(df_apl_dent_2022)

--------------------------------------------------
2 - Chargement APL chirurgiens-dentistes ...
34,955 lignes chargées
Colonnes : ['code_insee_comm', 'nom_commune', 'apl_dentistes', 'Population standardisée 2021 pour les chirurgiens-dentistes', 'Population totale 2021']

🔍 Vérification des valeurs :
  code_insee_comm              nom_commune  \
0             NaN                      NaN
1           01001  L'Abergement-Clémenciat
2           01002    L'Abergement-de-Varey
3           01004        Ambérieu-en-Bugey
4           01005      Ambérieux-en-Dombes
5           01006                  Ambléon
6           01007                 Ambronay
7           01008                 Ambutrix
8           01009         Andert-et-Condon
9           01010                Anglefort

                                apl_dentistes
0  En ETP pour 100 000 habitants standardisés
1                                       35.27
2                                      36.427
3                                      59.621
4                                      50.539
5                                      10.929
6                                      61.351
7                                      64.479
8                                      35.752
9                                      19.385

## 3  - Chargement APL Infirmières

In [98]:
# 3 Infirmiéres
print('-'*50)
print("3 - Chargement APL Infirmières ...")
file_path = DATA_DIR / 'apl_infirmieres.xlsx'
df_apl_infirmiers = pd.read_excel(
    file_path,
    sheet_name='APL 2023',
    skiprows=8,
    dtype={'Code commune INSEE': str}
).rename(columns={'APL aux infirmières': 'apl_infirmiers',
                  'Code commune INSEE': 'code_insee_comm',
                  'Commune': 'nom_commune'}) 

print(f"{len(df_apl_infirmiers):,} lignes chargées")
print(f"Colonnes : {df_apl_infirmiers.columns.tolist()}")
print("\n🔍 Vérification des valeurs :")
print(df_apl_infirmiers[['code_insee_comm', 'nom_commune', 'apl_infirmiers']].head(10))


df_apl_infirmiers_2022 = (
    pd.read_excel(
        file_path,
        sheet_name='APL 2022',
        skiprows=8,
        dtype={'Code commune INSEE': str}
    )
    .rename(columns={'APL aux infirmières': 'apl_infirmiers_2022',
                     'Code commune INSEE': 'code_insee_comm'})
    [['code_insee_comm', 'apl_infirmiers_2022']]
) 
dfs_2022.append(df_apl_infirmiers_2022)

--------------------------------------------------
3 - Chargement APL Infirmières ...
34,955 lignes chargées
Colonnes : ['code_insee_comm', 'nom_commune', 'apl_infirmiers', 'Population standardisée 2021 pour les infirmières', 'Population totale 2021']

🔍 Vérification des valeurs :
  code_insee_comm              nom_commune  \
0             NaN                      NaN
1           01001  L'Abergement-Clémenciat
2           01002    L'Abergement-de-Varey
3           01004        Ambérieu-en-Bugey
4           01005      Ambérieux-en-Dombes
5           01006                  Ambléon
6           01007                 Ambronay
7           01008                 Ambutrix
8           01009         Andert-et-Condon
9           01010                Anglefort

                               apl_infirmiers
0  En ETP pour 100 000 habitants standardisés
1                                     122.416
2                                     109.849
3                                     201.121
4                                     131.876
5                                      44.227
6                                      201.61
7                                     218.493
8                                     174.152
9                                     114.666

## 4  - Chargement APL kinés

In [99]:
# 4. Kinés
print('-'*50)
print("4 - Chargement APL kinésithérapeutes ...")
file_path = DATA_DIR / 'apl_kinesitherapeutes.xlsx'
df_apl_kines = pd.read_excel(
    file_path,
    sheet_name='APL 2023',
    skiprows=8,
    dtype={'Code commune INSEE': str}
).rename(columns={'APL aux kinésithérapeutes': 'apl_kines',
                  'Code commune INSEE': 'code_insee_comm',
                  'Commune': 'nom_commune'}) 

print(f"{len(df_apl_kines):,} lignes chargées")
print(f"Colonnes : {df_apl_kines.columns.tolist()}")

df_apl_kines_2022 = (
    pd.read_excel(
        file_path,
        sheet_name='APL 2022',
        skiprows=8,
        dtype={'Code commune INSEE': str}
    )
    .rename(columns={'APL aux kinésithérapeutes': 'apl_kines_2022',
                     'Code commune INSEE': 'code_insee_comm'})
    [['code_insee_comm', 'apl_kines_2022']]
) 
dfs_2022.append(df_apl_kines_2022)

--------------------------------------------------
4 - Chargement APL kinésithérapeutes ...
34,955 lignes chargées
Colonnes : ['code_insee_comm', 'nom_commune', 'apl_kines', 'Population standardisée 2021 pour les kinésithérapeutes', 'Population totale 2021']

## 5  - Chargement APL sages-femmes

In [100]:
# 5. Sages-femmes
print('-'*50)
print("5 - Chargement APL sages-femmes ...")
file_path = DATA_DIR / 'apl_sages_femmes.xlsx'
df_apl_sagesfemmes = pd.read_excel(
    file_path,
    sheet_name='APL 2023',
    skiprows=8,
    dtype={'Code commune INSEE': str}
).rename(columns={'APL aux sages-femmes': 'apl_sagesfemmes',
                  'Code commune INSEE': 'code_insee_comm',
                  'Commune': 'nom_commune'
                  })

print(f"{len(df_apl_sagesfemmes):,} lignes chargées")
print(f"Colonnes : {df_apl_sagesfemmes.columns.tolist()}")

df_apl_sagesfemmes_2022 = (
    pd.read_excel(
        file_path,
        sheet_name='APL 2022',
        skiprows=8,
        dtype={'Code commune INSEE': str}
    )
    .rename(columns={'APL aux sages-femmes': 'apl_sagesfemmes_2022',
                     'Code commune INSEE': 'code_insee_comm'})
    [['code_insee_comm', 'apl_sagesfemmes_2022']]
) 
dfs_2022.append(df_apl_sagesfemmes_2022)

--------------------------------------------------
5 - Chargement APL sages-femmes ...
34,955 lignes chargées
Colonnes : ['code_insee_comm', 'nom_commune', 'apl_sagesfemmes', 'Population féminine standardisée 2021 pour les sages-femmes', 'Population totale 2021', 'Population féminine 2021']

In [101]:
for i, df in enumerate(dfs_2022):
    if "code_insee_comm" not in df.columns:
        print(f"⚠️ Erreur au DataFrame index {i} !")
        print(f"Colonnes réelles : {df.columns.tolist()}")

In [102]:
from functools import reduce

df_apls_2022 = reduce(
    lambda left, right: pd.merge(left, right, on="code_insee_comm", how="outer"),
    dfs_2022
)

In [103]:


df_merged = df_apl_medecins\
    .merge(df_apl_dentistes[['code_insee_comm', 'apl_dentistes']], 
           left_on='code_insee_comm', right_on='code_insee_comm', how='left', suffixes=('', '_y'))\
    .merge(df_apl_infirmiers[['code_insee_comm', 'apl_infirmiers']], 
           left_on='code_insee_comm', right_on='code_insee_comm', how='left', suffixes=('', '_y'))\
    .merge(df_apl_kines[['code_insee_comm', 'apl_kines']], 
           left_on='code_insee_comm', right_on='code_insee_comm', how='left', suffixes=('', '_y'))\
    .merge(df_apl_sagesfemmes[['code_insee_comm', 'apl_sagesfemmes']], 
           left_on='code_insee_comm', right_on='code_insee_comm', how='left', suffixes=('', '_y'))


print(f"✅ {len(df_merged):,} communes avec apls après jointure")
print(f"Colonnes APL : {[c for c in df_merged.columns if 'apl_' in c]}")
print(df_merged.columns)

✅ 34,955 communes avec apls après jointure
Colonnes APL : ['apl_medecins', 'apl_65ans', 'apl_62ans', 'apl_60ans', 'apl_dentistes', 'apl_infirmiers', 'apl_kines', 'apl_sagesfemmes']
Index(['code_insee_comm', 'nom_commune', 'apl_medecins', 'apl_65ans',
       'apl_62ans', 'apl_60ans', 'pop_standard_2021', 'pop_totale_2021',
       'apl_dentistes', 'apl_infirmiers', 'apl_kines', 'apl_sagesfemmes'],
      dtype='object')

In [104]:
df_merged.isna().sum()

code_insee_comm      1
nom_commune          1
apl_medecins         0
apl_65ans            0
apl_62ans            0
apl_60ans            0
pop_standard_2021    0
pop_totale_2021      0
apl_dentistes        0
apl_infirmiers       0
apl_kines            0
apl_sagesfemmes      0
dtype: int64

In [105]:
df_merged.head()
#print(len(df_merged))

,code_insee_comm,nom_commune,apl_medecins,apl_65ans,apl_62ans,apl_60ans,pop_standard_2021,pop_totale_2021,apl_dentistes,apl_infirmiers,apl_kines,apl_sagesfemmes
0,NaN,NaN,En nombre de consultations/visites accessibles...,En nombre de consultations/visites accessibles...,En nombre de consultations/visites accessibles...,En nombre de consultations/visites accessibles...,En nombre d'habitants standardisés,En nombre d'habitants,En ETP pour 100 000 habitants standardisés,En ETP pour 100 000 habitants standardisés,En ETP pour 100 000 habitants standardisés,En ETP pour 100 000 habitantes standardisées
1,01001,L'Abergement-Clémenciat,1.942,1.881,1.623,1.455,838.154,832,35.27,122.416,46.259,26.842
2,01002,L'Abergement-de-Varey,2.376,1.767,1.503,1.333,255.723,267,36.427,109.849,51.106,14.058
3,01004,Ambérieu-en-Bugey,3.083,2.431,2.136,1.855,14575.887,14854,59.621,201.121,128.398,27.729
4,01005,Ambérieux-en-Dombes,3.706,3.648,3.015,2.998,1852.496,1897,50.539,131.876,113.357,30.5

In [106]:

#df_merged = df_merged[~df_merged['Commune'].isna()]

In [107]:
df_final = df_merged.copy()

In [108]:
df_apls_2022.columns

Index(['code_insee_comm', 'Commune', 'apl_medecins_2022', 'apl_65a_2022',
       'apl_62a_2022', 'apl_60a_2022',
       'Population standardisée 2020 pour la médecine générale',
       'Population totale 2020', 'apl_dentistes_2022', 'apl_infirmiers_2022',
       'apl_kines_2022', 'apl_sagesfemmes_2022'],
      dtype='object')

In [109]:
# Ajout des apls 2022
df_final["apl_medecins_2022"] = df_apls_2022["apl_medecins_2022"]
df_final["apl_dentistes_2022"] = df_apls_2022["apl_dentistes_2022"]
df_final["apl_infirmiers_2022"] = df_apls_2022["apl_infirmiers_2022"]
df_final["apl_kines_2022"] = df_apls_2022["apl_kines_2022"]
df_final["apl_sagesfemmes_2022"] = df_apls_2022["apl_sagesfemmes_2022"]

In [110]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34955 entries, 0 to 34954
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   code_insee_comm       34954 non-null  object
 1   nom_commune           34954 non-null  object
 2   apl_medecins          34955 non-null  object
 3   apl_65ans             34955 non-null  object
 4   apl_62ans             34955 non-null  object
 5   apl_60ans             34955 non-null  object
 6   pop_standard_2021     34955 non-null  object
 7   pop_totale_2021       34955 non-null  object
 8   apl_dentistes         34955 non-null  object
 9   apl_infirmiers        34955 non-null  object
 10  apl_kines             34955 non-null  object
 11  apl_sagesfemmes       34955 non-null  object
 12  apl_medecins_2022     34955 non-null  object
 13  apl_dentistes_2022    34955 non-null  object
 14  apl_infirmiers_2022   34955 non-null  object
 15  apl_kines_2022        34955 non-null  object
 16  apl_sagesfemmes_2022  34955 non-null  object
dtypes: object(17)
memory usage: 4.5+ MB

In [111]:
df_final.isna().sum()

code_insee_comm         1
nom_commune             1
apl_medecins            0
apl_65ans               0
apl_62ans               0
apl_60ans               0
pop_standard_2021       0
pop_totale_2021         0
apl_dentistes           0
apl_infirmiers          0
apl_kines               0
apl_sagesfemmes         0
apl_medecins_2022       0
apl_dentistes_2022      0
apl_infirmiers_2022     0
apl_kines_2022          0
apl_sagesfemmes_2022    0
dtype: int64

In [112]:
# supprimer la deuxiéme ligne d'entête
df_final.dropna(inplace=True)

In [113]:
# Calcul des deltas
df_final["delta_apl_medecins"] = df_final["apl_medecins"] - df_final["apl_medecins_2022"]
df_final["delta_apl_dentistes"] = df_final["apl_dentistes"] - df_final["apl_dentistes_2022"]
df_final["delta_apl_infirmiers"] = df_final["apl_infirmiers"] - df_final["apl_infirmiers_2022"]
df_final["delta_apl_kines"] = df_final["apl_kines"] - df_final["apl_kines_2022"]
df_final["delta_apl_sagesfemmes"] = df_final["apl_sagesfemmes"] - df_final["apl_sagesfemmes_2022"]

In [114]:
# Supprimer les colonnes 2022
cols_2022 = [ "apl_medecins_2022", "apl_dentistes_2022", "apl_infirmiers_2022", "apl_kines_2022", "apl_sagesfemmes_2022" ]

In [115]:
df_final.columns

Index(['code_insee_comm', 'nom_commune', 'apl_medecins', 'apl_65ans',
       'apl_62ans', 'apl_60ans', 'pop_standard_2021', 'pop_totale_2021',
       'apl_dentistes', 'apl_infirmiers', 'apl_kines', 'apl_sagesfemmes',
       'apl_medecins_2022', 'apl_dentistes_2022', 'apl_infirmiers_2022',
       'apl_kines_2022', 'apl_sagesfemmes_2022', 'delta_apl_medecins',
       'delta_apl_dentistes', 'delta_apl_infirmiers', 'delta_apl_kines',
       'delta_apl_sagesfemmes'],
      dtype='object')

In [116]:
# Standardiser les APLs
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Ajouter une colonne pour chaque APL standardisée 'NomColonne'_std
for col in ['apl_medecins', 'apl_dentistes', 'apl_infirmiers', 'apl_kines', 'apl_sagesfemmes']:
    df_final[col + '_std'] = scaler.fit_transform(df_final[[col]])

In [117]:
weights = {
    'apl_med_consult': 0.35,
    'apl_inf_etp': 0.25,
    'apl_kine_etp': 0.20,
    'apl_dent_etp': 0.15,
    'apl_sf_etp': 0.05
}

In [118]:
df_final['score_apl'] = (
    df_final['apl_medecins_std'] * weights['apl_med_consult'] +
    df_final['apl_infirmiers_std'] * weights['apl_inf_etp'] +
    df_final['apl_kines_std'] * weights['apl_kine_etp'] +
    df_final['apl_dentistes_std'] * weights['apl_dent_etp'] +
    df_final['apl_sagesfemmes_std'] * weights['apl_sf_etp']
)

In [119]:
# Catégorisation en quintiles
df_final['quintile_apl_nat'] = pd.qcut(df_final['score_apl'], q=5, labels=['Q1 (très faible)', 'Q2 (faible)', 'Q3 (moyen)', 'Q4 (bon)', 'Q5 (très bon)'])

In [120]:
#df_final.drop(columns='categorie_nationale', inplace=True)
df_final.head()

,code_insee_comm,nom_commune,apl_medecins,apl_65ans,apl_62ans,apl_60ans,pop_standard_2021,pop_totale_2021,apl_dentistes,apl_infirmiers,...,delta_apl_infirmiers,delta_apl_kines,delta_apl_sagesfemmes,apl_medecins_std,apl_dentistes_std,apl_infirmiers_std,apl_kines_std,apl_sagesfemmes_std,score_apl,quintile_apl_nat
1,01001,L'Abergement-Clémenciat,1.942,1.881,1.623,1.455,838.154,832,35.27,122.416,...,14.903,-2.978,12.955,-0.772546,0.026716,0.044420,-0.610034,1.186782,-0.317946,Q2 (faible)
2,01002,L'Abergement-de-Varey,2.376,1.767,1.503,1.333,255.723,267,36.427,109.849,...,-95.639,-71.597,-14.449,-0.442053,0.076964,-0.140549,-0.510025,-0.214993,-0.291066,Q2 (faible)
3,01004,Ambérieu-en-Bugey,3.083,2.431,2.136,1.855,14575.887,14854,59.621,201.121,...,60.097,24.294,-1.842,0.096332,1.084259,1.202849,1.084761,1.284043,0.778222,Q5 (très bon)
4,01005,Ambérieux-en-Dombes,3.706,3.648,3.015,2.998,1852.496,1897,50.539,131.876,...,85.359,92.246,17.529,0.570751,0.689836,0.183658,0.774416,1.587885,0.583430,Q5 (très bon)
5,01006,Ambléon,0.889,0.775,0.648,0.57,121.314,113,10.929,44.227,...,-153.632,-89.582,-15.397,-1.574412,-1.030392,-1.106414,-1.130735,-0.453044,-1.231006,Q1 (très faible)

In [121]:
df_final.columns

Index(['code_insee_comm', 'nom_commune', 'apl_medecins', 'apl_65ans',
       'apl_62ans', 'apl_60ans', 'pop_standard_2021', 'pop_totale_2021',
       'apl_dentistes', 'apl_infirmiers', 'apl_kines', 'apl_sagesfemmes',
       'apl_medecins_2022', 'apl_dentistes_2022', 'apl_infirmiers_2022',
       'apl_kines_2022', 'apl_sagesfemmes_2022', 'delta_apl_medecins',
       'delta_apl_dentistes', 'delta_apl_infirmiers', 'delta_apl_kines',
       'delta_apl_sagesfemmes', 'apl_medecins_std', 'apl_dentistes_std',
       'apl_infirmiers_std', 'apl_kines_std', 'apl_sagesfemmes_std',
       'score_apl', 'quintile_apl_nat'],
      dtype='object')

In [ ]:
df_final.to_csv('../data/processed/data/commune/raw_comm_score_apl_niv0.csv', index=False)
df_final.to_parquet('../data/processed/data/commune/raw_comm_score_apl_niv0.parquet', index=False)

In [123]:
# Colonnes à forcer en STRING
df = df_final
cols_fix = [c for c in df.columns if 'code' in c.lower() or 'siren' in c.lower()]

# Générer schéma
schema = []
for col in df.columns:
    bq_type = "STRING" if col in cols_fix or df[col].dtype == 'object' else \
              "INTEGER" if df[col].dtype in ['int64', 'int32'] else \
              "FLOAT" if df[col].dtype in ['float64', 'float32'] else "STRING"
    schema.append({"name": col, "type": bq_type, "mode": "NULLABLE"})

schema

[{'name': 'code_insee_comm', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'nom_commune', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'apl_medecins', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'apl_65ans', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'apl_62ans', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'apl_60ans', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'pop_standard_2021', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'pop_totale_2021', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'apl_dentistes', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'apl_infirmiers', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'apl_kines', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'apl_sagesfemmes', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'apl_medecins_2022', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'apl_dentistes_2022', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'apl_infirmiers_2022', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'apl_kines_2022', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'apl_sagesfemmes_2022', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'delta_apl_medecins', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'delta_apl_dentistes', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'delta_apl_infirmiers', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'delta_apl_kines', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'delta_apl_sagesfemmes', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'apl_medecins_std', 'type': 'FLOAT', 'mode': 'NULLABLE'},
 {'name': 'apl_dentistes_std', 'type': 'FLOAT', 'mode': 'NULLABLE'},
 {'name': 'apl_infirmiers_std', 'type': 'FLOAT', 'mode': 'NULLABLE'},
 {'name': 'apl_kines_std', 'type': 'FLOAT', 'mode': 'NULLABLE'},
 {'name': 'apl_sagesfemmes_std', 'type': 'FLOAT', 'mode': 'NULLABLE'},
 {'name': 'score_apl', 'type': 'FLOAT', 'mode': 'NULLABLE'},
 {'name': 'quintile_apl_nat', 'type': 'STRING', 'mode': 'NULLABLE'}]