In [2]:
import pandas as pd


Base des zones d'emploi 2020 au 1er janvier 2025

https://www.insee.fr/fr/information/4652957

Fichier : ZE2020_au_01-01-2025xlsx

In [3]:
FILE_PATH = '../data/raw/territoires/ZE2020_au_01-01-2025.xlsx'

from openpyxl import load_workbook 
import pandas as pd 
wb = load_workbook(FILE_PATH, read_only=True, data_only=True) 
sheets = wb.sheetnames 
dfs = {name: pd.DataFrame(wb[name].values) for name in sheets}

dfs.keys()

dict_keys(['ZE2020', 'Composition_communale', 'Variables', 'Documentation'])

In [4]:
print("1 - Chargement Zone d'emploi ...")
df_ze = pd.read_excel(
    FILE_PATH,
    sheet_name='ZE2020',
    skiprows=5,
    dtype={'ZE2020': str}
)

1 - Chargement Zone d'emploi ...

In [5]:
df_ze.head()

  ZE2020            LIBZE2020  NB_COM
0   0051              Alençon     184
1   0052                Arles      20
2   0053              Avignon      36
3   0054             Beauvais     327
4   0055  Bollène-Pierrelatte      29

In [6]:
df_ze.to_csv('../data/raw/geo/zone_emploi.csv', index=False)
df_ze.to_parquet('../data/raw/geo/zone_emploi.parquet', index=False)

In [7]:
print("1 - Chargement lien zone-communes ...")
df_ze_comm = pd.read_excel(
    FILE_PATH,
    sheet_name='Composition_communale',
    skiprows=5,
    dtype={'ZE2020': str}
)

1 - Chargement lien zone-communes ...

In [8]:
df_ze_comm.head()

,CODGEO,LIBGEO,ZE2020,LIBZE2020,ZE_PARTIE_REG,DEP,REG
0,01001,L'Abergement-Clémenciat,8405,Bourg-en-Bresse,NaN,01,84
1,01002,L'Abergement-de-Varey,8405,Bourg-en-Bresse,NaN,01,84
2,01004,Ambérieu-en-Bugey,8405,Bourg-en-Bresse,NaN,01,84
3,01005,Ambérieux-en-Dombes,8434,Villefranche-sur-Saône,NaN,01,84
4,01006,Ambléon,8404,Belley,NaN,01,84

In [32]:
df_ze_comm.to_csv('../data/raw/geo/zone_emploi_communes.csv', index=False)
df_ze_comm.to_parquet('../data/raw/geo/zone_emploi_communes.parquet', index=False)

Zone d'emploi 2020 - France

https://public.opendatasoft.com/explore/assets/georef-france-zone-emploi-2020/export/

In [10]:
import geopandas as gpd

df_georef_ze = gpd.read_file('../data/raw/territoires/georef-france-zone-emploi-2020.geojson')

In [11]:
df_georef_ze.head()

,geo_point_2d,year,reg_code,reg_name,dep_code,dep_name,ze2020_code,ze2020_current_code,ze2020_name,ze2020_name_upper,ze2020_name_lower,ze2020_area_code,ze2020_type,geometry
0,"{'lon': 3.4988500668623783, 'lat': 50.34311023...",2025,[32],[Hauts-de-France],[59],[Nord],[3222],[3222],[Valenciennes],VALENCIENNES,valenciennes,FXX,zone emploi 2020,"POLYGON ((3.25214 50.27971, 3.26829 50.27815, ..."
1,"{'lon': 1.3813105025246752, 'lat': 44.48680417...",2025,[76],[Occitanie],"[46, 82]","[Lot, Tarn-et-Garonne]",[7607],[7607],[Cahors],CAHORS,cahors,FXX,zone emploi 2020,"POLYGON ((1.26683 44.25163, 1.28452 44.25266, ..."
2,"{'lon': 2.5274145032619626, 'lat': 47.59703357...",2025,[24],[Centre-Val de Loire],"[18, 45]","[Cher, Loiret]",[2407],[2407],[Gien],GIEN,gien,FXX,zone emploi 2020,"POLYGON ((2.32316 47.35709, 2.33008 47.35703, ..."
3,"{'lon': 6.743588542261566, 'lat': 45.894586698...",2025,[84],[Auvergne-Rhône-Alpes],"[73, 74]","[Haute-Savoie, Savoie]",[8418],[8418],[Le Mont Blanc],LE MONT BLANC,le mont blanc,FXX,zone emploi 2020,"POLYGON ((6.44419 45.83138, 6.45388 45.81934, ..."
4,"{'lon': 6.62150467104502, 'lat': 49.0972242351...",2025,[44],[Grand Est],[57],[Moselle],[4416],[4416],[Saint-Avold],SAINT-AVOLD,saint-avold,FXX,zone emploi 2020,"POLYGON ((6.50019 48.8943, 6.51468 48.8933, 6...."

In [12]:
df_georef_ze.shape

(306, 14)

In [13]:
df_georef_ze.columns

Index(['geo_point_2d', 'year', 'reg_code', 'reg_name', 'dep_code', 'dep_name',
       'ze2020_code', 'ze2020_current_code', 'ze2020_name',
       'ze2020_name_upper', 'ze2020_name_lower', 'ze2020_area_code',
       'ze2020_type', 'geometry'],
      dtype='object')

In [14]:
df_ze_final = df_georef_ze.copy()
df_ze_final = df_ze_final.drop(columns=['year','ze2020_current_code', 'ze2020_name_upper', 'ze2020_name_lower', 'ze2020_area_code', 'ze2020_type'])
df_ze_final.head()

,geo_point_2d,reg_code,reg_name,dep_code,dep_name,ze2020_code,ze2020_name,geometry
0,"{'lon': 3.4988500668623783, 'lat': 50.34311023...",[32],[Hauts-de-France],[59],[Nord],[3222],[Valenciennes],"POLYGON ((3.25214 50.27971, 3.26829 50.27815, ..."
1,"{'lon': 1.3813105025246752, 'lat': 44.48680417...",[76],[Occitanie],"[46, 82]","[Lot, Tarn-et-Garonne]",[7607],[Cahors],"POLYGON ((1.26683 44.25163, 1.28452 44.25266, ..."
2,"{'lon': 2.5274145032619626, 'lat': 47.59703357...",[24],[Centre-Val de Loire],"[18, 45]","[Cher, Loiret]",[2407],[Gien],"POLYGON ((2.32316 47.35709, 2.33008 47.35703, ..."
3,"{'lon': 6.743588542261566, 'lat': 45.894586698...",[84],[Auvergne-Rhône-Alpes],"[73, 74]","[Haute-Savoie, Savoie]",[8418],[Le Mont Blanc],"POLYGON ((6.44419 45.83138, 6.45388 45.81934, ..."
4,"{'lon': 6.62150467104502, 'lat': 49.0972242351...",[44],[Grand Est],[57],[Moselle],[4416],[Saint-Avold],"POLYGON ((6.50019 48.8943, 6.51468 48.8933, 6...."

In [15]:
if "geo_point_2d" in df_ze_final.columns:
    df_ze_final["lon"] = df_ze_final["geo_point_2d"].apply(lambda d: d.get("lon") if isinstance(d, dict) else None) 
    df_ze_final["lat"] = df_ze_final["geo_point_2d"].apply(lambda d: d.get("lat") if isinstance(d, dict) else None)

In [16]:
for col in ["reg_code", "reg_name", "dep_code", "dep_name", "ze2020_code", "ze2020_name"]: 
    df_ze_final[col] = df_ze_final[col].apply(lambda x: x[0] if isinstance(x, list) and len(x) == 1 else x)

df_ze_final.head()

,geo_point_2d,reg_code,reg_name,dep_code,dep_name,ze2020_code,ze2020_name,geometry,lon,lat
0,"{'lon': 3.4988500668623783, 'lat': 50.34311023...",[32],[Hauts-de-France],[59],[Nord],[3222],[Valenciennes],"POLYGON ((3.25214 50.27971, 3.26829 50.27815, ...",3.498850,50.343110
1,"{'lon': 1.3813105025246752, 'lat': 44.48680417...",[76],[Occitanie],"[46, 82]","[Lot, Tarn-et-Garonne]",[7607],[Cahors],"POLYGON ((1.26683 44.25163, 1.28452 44.25266, ...",1.381311,44.486804
2,"{'lon': 2.5274145032619626, 'lat': 47.59703357...",[24],[Centre-Val de Loire],"[18, 45]","[Cher, Loiret]",[2407],[Gien],"POLYGON ((2.32316 47.35709, 2.33008 47.35703, ...",2.527415,47.597034
3,"{'lon': 6.743588542261566, 'lat': 45.894586698...",[84],[Auvergne-Rhône-Alpes],"[73, 74]","[Haute-Savoie, Savoie]",[8418],[Le Mont Blanc],"POLYGON ((6.44419 45.83138, 6.45388 45.81934, ...",6.743589,45.894587
4,"{'lon': 6.62150467104502, 'lat': 49.0972242351...",[44],[Grand Est],[57],[Moselle],[4416],[Saint-Avold],"POLYGON ((6.50019 48.8943, 6.51468 48.8933, 6....",6.621505,49.097224

In [17]:
import numpy as np

def unwrap_array(v):
    # Cas 1 : numpy array
    if isinstance(v, np.ndarray):
        if len(v) == 1:
            return v[0]              # ex: array(['32']) → '32'
        else:
            return ",".join(map(str, v))  # ex: array(['46','82']) → '46,82'
    return v

cols = ["reg_code", "reg_name", "dep_code", "dep_name", "ze2020_code", "ze2020_name"]

for col in cols:
    df_ze_final[col] = df_ze_final[col].apply(unwrap_array)

In [18]:
df_ze_final

,geo_point_2d,reg_code,reg_name,dep_code,dep_name,ze2020_code,ze2020_name,geometry,lon,lat
0,"{'lon': 3.4988500668623783, 'lat': 50.34311023...",32,Hauts-de-France,59,Nord,3222,Valenciennes,"POLYGON ((3.25214 50.27971, 3.26829 50.27815, ...",3.498850,50.343110
1,"{'lon': 1.3813105025246752, 'lat': 44.48680417...",76,Occitanie,"46,82","Lot,Tarn-et-Garonne",7607,Cahors,"POLYGON ((1.26683 44.25163, 1.28452 44.25266, ...",1.381311,44.486804
2,"{'lon': 2.5274145032619626, 'lat': 47.59703357...",24,Centre-Val de Loire,"18,45","Cher,Loiret",2407,Gien,"POLYGON ((2.32316 47.35709, 2.33008 47.35703, ...",2.527415,47.597034
3,"{'lon': 6.743588542261566, 'lat': 45.894586698...",84,Auvergne-Rhône-Alpes,"73,74","Haute-Savoie,Savoie",8418,Le Mont Blanc,"POLYGON ((6.44419 45.83138, 6.45388 45.81934, ...",6.743589,45.894587
4,"{'lon': 6.62150467104502, 'lat': 49.0972242351...",44,Grand Est,57,Moselle,4416,Saint-Avold,"POLYGON ((6.50019 48.8943, 6.51468 48.8933, 6....",6.621505,49.097224
...,...,...,...,...,...,...,...,...,...,...
301,"{'lon': 3.294701664172079, 'lat': 46.546604559...",84,Auvergne-Rhône-Alpes,03,Allier,8424,Moulins,"POLYGON ((2.62381 46.6567, 2.63641 46.64625, 2...",3.294702,46.546605
302,"{'lon': 4.031095624013338, 'lat': 46.049716772...",84,Auvergne-Rhône-Alpes,42,Loire,8426,Roanne,"POLYGON ((3.69402 45.93073, 3.71854 45.92399, ...",4.031096,46.049717
303,"{'lon': -1.4503561782269032, 'lat': 46.6999665...",52,Pays de la Loire,85,Vendée,5210,La Roche-sur-Yon,"POLYGON ((-1.41286 46.41869, -1.38859 46.42014...",-1.450356,46.699967
304,"{'lon': 0.226914030061894, 'lat': 49.078353617...",28,Normandie,"14,61","Calvados,Orne",2814,Lisieux,"POLYGON ((0.22704 48.84827, 0.24427 48.83808, ...",0.226914,49.078354
305,"{'lon': -60.87783194149753, 'lat': 14.52490299...",02,Martinique,972,Martinique,0205,Le Sud,"POLYGON ((-60.91085 14.46891, -60.91226 14.462...",-60.877832,14.524903

In [22]:
df_geom_ze = df_ze_final.copy()

df_geom_ze = df_geom_ze[['ze2020_code', 'ze2020_name', 'geometry', 'lon', 'lat']]

df_geom_ze.head()

,ze2020_code,ze2020_name,geometry,lon,lat
0,3222,Valenciennes,"POLYGON ((3.25214 50.27971, 3.26829 50.27815, ...",3.498850,50.343110
1,7607,Cahors,"POLYGON ((1.26683 44.25163, 1.28452 44.25266, ...",1.381311,44.486804
2,2407,Gien,"POLYGON ((2.32316 47.35709, 2.33008 47.35703, ...",2.527415,47.597034
3,8418,Le Mont Blanc,"POLYGON ((6.44419 45.83138, 6.45388 45.81934, ...",6.743589,45.894587
4,4416,Saint-Avold,"POLYGON ((6.50019 48.8943, 6.51468 48.8933, 6....",6.621505,49.097224

In [23]:
df_geom_ze.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [27]:
def simplify_geom(gdf, tolerance=20):
    # Reprojection en Lambert 93 car pandas peut sans qu'on le sache le charger en WGS84 
    # la simplification est plus efficace dans un système métrique
    gdf = gdf.to_crs(2154)

    # Correction + simplification + correction
    gdf["geometry"] = (
        gdf["geometry"]
        .buffer(0)
        .simplify(tolerance, preserve_topology=False)
        .buffer(0)
    )

    # Reprojection finale en WGS84 pour le web
    return gdf.to_crs(4326)

In [28]:
df_geom_ze = simplify_geom(df_geom_ze, 100)

In [30]:
df_geom_ze.to_csv('../data/processed/geom/zone_emploi_geom_simplified.csv', index=False)
df_geom_ze.to_parquet('../data/processed/geom/zone_emploi_geom_simplified.parquet', index=False)

In [31]:
df_geom_ze.columns

Index(['ze2020_code', 'ze2020_name', 'geometry', 'lon', 'lat'], dtype='object')